### ISSUE TITLE
Move to yarnplugins

### ISSUE THREAD

**Issue by eps1lon** [eps1lon/yarn-plugin-deduplicate#9]
Since we have a dedicate org for community plugins this plugin could live under @yarnplugins.

Question is whether it stay a standalone repo or move to https://github.com/yarnplugins/yarn-plugins.

Standalone repo seems easier to keep the CI intact and we don't have to deal with integrating git repositories.

Any preference @koistya?

**Comment by koistya** [comment]
Standalone repo will work, @yarnplugins will prettify download URLs and provide download statistics, similarly to community GitHub Actions.

Pushing to the shared repo will work as well, can be simpler to maintain tooling and CI workflow.

I personally leaning towards a shared repo, at least for new plugins that can be convenient.

**Comment by eps1lon** [comment]
Moved the repo:

> Moving repository to yarnplugins/yarn-plugin-deduplicate. This may take a few minutes.
